### ISSUE TITLE
Code Reformat & OOP Construct

### ISSUE THREAD

**Issue by PK-cod3ch3mist** [PK-cod3ch3mist/ASCII-Media-Player#11]
The present code is messy and redundant in many areas. It will be better if the code can be modularised and packaged into one class. It will also allow to wrap the curses function upon the code.

Requirements:
- Create a class called `AMP` that will have all functions in it
- Remove/merge redundant functions `read_media` and `read_media_sub`
- Add options for tuning the functions

**Comment by Vishesh-dd4723** [comment]
#12

**Comment by PK-cod3ch3mist** [comment]
Resolved by PR #12
