### ISSUE TITLE
New logo needed!

### ISSUE THREAD

**Issue by PK-cod3ch3mist** [PK-cod3ch3mist/ASCII-Media-Player#18]
The present logo is too simplistic and does not convey graphically the essence of ASCII Media Player.
Needed a new logo that is:
- Minimal (or not if it is really impressive)
- Conveys the essence of ASCII Media Player and text based interfaces in general
- In SVG format

Please discuss and show the logo first in the discussion here before raising a PR.

**Comment by yashee99** [comment]
Hello @PK-cod3ch3mist, I have an idea for the ASCII Media Player logo. Basically I think we can design a colourful play button and run it through the python script to get a ASCII style logo. What do you think about it?

**Comment by PK-cod3ch3mist** [comment]
Sounds good! Submit a PR regarding this, and let me see if the logo works.

**Comment by PK-cod3ch3mist** [comment]
Hi @yashee99. I think we should not run the logo through the ASCII media player script. This is because the logo is generally viewed at small sizes and thus any detail of the ASCII characters would be lost, making their presence meaningless. So in your PR, submit the original design you thought.

**Comment by PK-cod3ch3mist** [comment]
Hi @yashee99. I think we should not run the logo through the ASCII media player script. This is because the logo is generally viewed at small sizes and thus any detail of the ASCII characters would be lost, making their presence meaningless. So in your PR, submit the original design you thought.
