### ISSUE TITLE
Add play/pause functionality

### ISSUE THREAD

**Issue by PK-cod3ch3mist** [PK-cod3ch3mist/ASCII-Media-Player#3]
### Add a command/key that allows user to pause/play the video render
Add a function that waits for a play pause keypress and in case of the key being pressed/event happening, pauses (or plays) the video, i.e. pauses the rendering at the current frame.

**Comment by JeremiasFuentes** [comment]
Hello, can i work on this?

**Comment by PK-cod3ch3mist** [comment]
Yeah sure @JeremiasFuentes. Feel free to contribute

**Comment by PK-cod3ch3mist** [comment]
### Enhancing play/pause functionality
Though @JeremiasFuentes did provide a solution for the problem, I am welcome to other solutions that use fewer dependencies (use vanilla modules). 
This is mainly because the **keyboard** module requires administrator/root privileges for linux systems and is experimental in macOS.
